//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloundGamingBD
{


    public partial class _Default
    {

        /// <summary>
        /// Control lblNombreUsuario.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNombreUsuario;

        /// <summary>
        /// Control hlkMisJuegos.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink hlkMisJuegos;

        /// <summary>
        /// Control hlkConfiguracion.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink hlkConfiguracion;

        /// <summary>
        /// Control btnEstadisticas.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnEstadisticas;
    }
}
